local_planner:
    ros__parameters:
        max_sensor_range_: 15.0
        min_sensor_range_: 0.2
        pitch_cost_param_: 25.0
        yaw_cost_param_: 3.0
        velocity_cost_param_: 6000.0
        obstacle_cost_param_: 8.50
        tree_heuristic_weight_: 35.0
        goal_z_param: 3.5
        timeout_startup_: 5.0
        timeout_critical_: 0.5
        timeout_termination_: 15.0
        max_point_age_s_: 20.0
        min_num_points_per_cell_: 25 # Tune to your sensor requirements!
        smoothing_speed_xy_: 10.0
        smoothing_speed_z_: 3.0
        smoothing_margin_degrees_: 40.0
        tree_node_distance_: 1.0
        children_per_node_: 8
        n_expanded_nodes_: 10
        heading_cost_param_: 0.5
        no_progress_slope_: -0.0007
        smooth_cost_param_: 1.5
        tree_discount_factor_: 0.8
